# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/icecube45/dash

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/icecube45/dash

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/icecube45/dash/CMakeFiles /home/icecube45/dash//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/icecube45/dash/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ia

# Build rule for target.
ia: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ia
.PHONY : ia

# fast build rule for target.
ia/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/build
.PHONY : ia/fast

#=============================================================================
# Target rules for targets named InfinitiG37

# Build rule for target.
InfinitiG37: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 InfinitiG37
.PHONY : InfinitiG37

# fast build rule for target.
InfinitiG37/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InfinitiG37.dir/build.make CMakeFiles/InfinitiG37.dir/build
.PHONY : InfinitiG37/fast

#=============================================================================
# Target rules for targets named KF5BluezQt_QCH

# Build rule for target.
KF5BluezQt_QCH: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 KF5BluezQt_QCH
.PHONY : KF5BluezQt_QCH

# fast build rule for target.
KF5BluezQt_QCH/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KF5BluezQt_QCH.dir/build.make CMakeFiles/KF5BluezQt_QCH.dir/build
.PHONY : KF5BluezQt_QCH/fast

#=============================================================================
# Target rules for targets named ia_autogen

# Build rule for target.
ia_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ia_autogen
.PHONY : ia_autogen

# fast build rule for target.
ia_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia_autogen.dir/build.make CMakeFiles/ia_autogen.dir/build
.PHONY : ia_autogen/fast

#=============================================================================
# Target rules for targets named InfinitiG37_autogen

# Build rule for target.
InfinitiG37_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 InfinitiG37_autogen
.PHONY : InfinitiG37_autogen

# fast build rule for target.
InfinitiG37_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InfinitiG37_autogen.dir/build.make CMakeFiles/InfinitiG37_autogen.dir/build
.PHONY : InfinitiG37_autogen/fast

InfinitiG37_autogen/mocs_compilation.o: InfinitiG37_autogen/mocs_compilation.cpp.o

.PHONY : InfinitiG37_autogen/mocs_compilation.o

# target to build an object file
InfinitiG37_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InfinitiG37.dir/build.make CMakeFiles/InfinitiG37.dir/InfinitiG37_autogen/mocs_compilation.cpp.o
.PHONY : InfinitiG37_autogen/mocs_compilation.cpp.o

InfinitiG37_autogen/mocs_compilation.i: InfinitiG37_autogen/mocs_compilation.cpp.i

.PHONY : InfinitiG37_autogen/mocs_compilation.i

# target to preprocess a source file
InfinitiG37_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InfinitiG37.dir/build.make CMakeFiles/InfinitiG37.dir/InfinitiG37_autogen/mocs_compilation.cpp.i
.PHONY : InfinitiG37_autogen/mocs_compilation.cpp.i

InfinitiG37_autogen/mocs_compilation.s: InfinitiG37_autogen/mocs_compilation.cpp.s

.PHONY : InfinitiG37_autogen/mocs_compilation.s

# target to generate assembly for a file
InfinitiG37_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InfinitiG37.dir/build.make CMakeFiles/InfinitiG37.dir/InfinitiG37_autogen/mocs_compilation.cpp.s
.PHONY : InfinitiG37_autogen/mocs_compilation.cpp.s

ia_autogen/GBFAFXFCVO/qrc_resources.o: ia_autogen/GBFAFXFCVO/qrc_resources.cpp.o

.PHONY : ia_autogen/GBFAFXFCVO/qrc_resources.o

# target to build an object file
ia_autogen/GBFAFXFCVO/qrc_resources.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/ia_autogen/GBFAFXFCVO/qrc_resources.cpp.o
.PHONY : ia_autogen/GBFAFXFCVO/qrc_resources.cpp.o

ia_autogen/GBFAFXFCVO/qrc_resources.i: ia_autogen/GBFAFXFCVO/qrc_resources.cpp.i

.PHONY : ia_autogen/GBFAFXFCVO/qrc_resources.i

# target to preprocess a source file
ia_autogen/GBFAFXFCVO/qrc_resources.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/ia_autogen/GBFAFXFCVO/qrc_resources.cpp.i
.PHONY : ia_autogen/GBFAFXFCVO/qrc_resources.cpp.i

ia_autogen/GBFAFXFCVO/qrc_resources.s: ia_autogen/GBFAFXFCVO/qrc_resources.cpp.s

.PHONY : ia_autogen/GBFAFXFCVO/qrc_resources.s

# target to generate assembly for a file
ia_autogen/GBFAFXFCVO/qrc_resources.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/ia_autogen/GBFAFXFCVO/qrc_resources.cpp.s
.PHONY : ia_autogen/GBFAFXFCVO/qrc_resources.cpp.s

ia_autogen/mocs_compilation.o: ia_autogen/mocs_compilation.cpp.o

.PHONY : ia_autogen/mocs_compilation.o

# target to build an object file
ia_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/ia_autogen/mocs_compilation.cpp.o
.PHONY : ia_autogen/mocs_compilation.cpp.o

ia_autogen/mocs_compilation.i: ia_autogen/mocs_compilation.cpp.i

.PHONY : ia_autogen/mocs_compilation.i

# target to preprocess a source file
ia_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/ia_autogen/mocs_compilation.cpp.i
.PHONY : ia_autogen/mocs_compilation.cpp.i

ia_autogen/mocs_compilation.s: ia_autogen/mocs_compilation.cpp.s

.PHONY : ia_autogen/mocs_compilation.s

# target to generate assembly for a file
ia_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/ia_autogen/mocs_compilation.cpp.s
.PHONY : ia_autogen/mocs_compilation.cpp.s

plugins/infiniti_g37.o: plugins/infiniti_g37.cpp.o

.PHONY : plugins/infiniti_g37.o

# target to build an object file
plugins/infiniti_g37.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InfinitiG37.dir/build.make CMakeFiles/InfinitiG37.dir/plugins/infiniti_g37.cpp.o
.PHONY : plugins/infiniti_g37.cpp.o

plugins/infiniti_g37.i: plugins/infiniti_g37.cpp.i

.PHONY : plugins/infiniti_g37.i

# target to preprocess a source file
plugins/infiniti_g37.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InfinitiG37.dir/build.make CMakeFiles/InfinitiG37.dir/plugins/infiniti_g37.cpp.i
.PHONY : plugins/infiniti_g37.cpp.i

plugins/infiniti_g37.s: plugins/infiniti_g37.cpp.s

.PHONY : plugins/infiniti_g37.s

# target to generate assembly for a file
plugins/infiniti_g37.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InfinitiG37.dir/build.make CMakeFiles/InfinitiG37.dir/plugins/infiniti_g37.cpp.s
.PHONY : plugins/infiniti_g37.cpp.s

src/app/bluetooth.o: src/app/bluetooth.cpp.o

.PHONY : src/app/bluetooth.o

# target to build an object file
src/app/bluetooth.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/bluetooth.cpp.o
.PHONY : src/app/bluetooth.cpp.o

src/app/bluetooth.i: src/app/bluetooth.cpp.i

.PHONY : src/app/bluetooth.i

# target to preprocess a source file
src/app/bluetooth.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/bluetooth.cpp.i
.PHONY : src/app/bluetooth.cpp.i

src/app/bluetooth.s: src/app/bluetooth.cpp.s

.PHONY : src/app/bluetooth.s

# target to generate assembly for a file
src/app/bluetooth.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/bluetooth.cpp.s
.PHONY : src/app/bluetooth.cpp.s

src/app/config.o: src/app/config.cpp.o

.PHONY : src/app/config.o

# target to build an object file
src/app/config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/config.cpp.o
.PHONY : src/app/config.cpp.o

src/app/config.i: src/app/config.cpp.i

.PHONY : src/app/config.i

# target to preprocess a source file
src/app/config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/config.cpp.i
.PHONY : src/app/config.cpp.i

src/app/config.s: src/app/config.cpp.s

.PHONY : src/app/config.s

# target to generate assembly for a file
src/app/config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/config.cpp.s
.PHONY : src/app/config.cpp.s

src/app/modules/brightness.o: src/app/modules/brightness.cpp.o

.PHONY : src/app/modules/brightness.o

# target to build an object file
src/app/modules/brightness.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/modules/brightness.cpp.o
.PHONY : src/app/modules/brightness.cpp.o

src/app/modules/brightness.i: src/app/modules/brightness.cpp.i

.PHONY : src/app/modules/brightness.i

# target to preprocess a source file
src/app/modules/brightness.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/modules/brightness.cpp.i
.PHONY : src/app/modules/brightness.cpp.i

src/app/modules/brightness.s: src/app/modules/brightness.cpp.s

.PHONY : src/app/modules/brightness.s

# target to generate assembly for a file
src/app/modules/brightness.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/modules/brightness.cpp.s
.PHONY : src/app/modules/brightness.cpp.s

src/app/shortcuts.o: src/app/shortcuts.cpp.o

.PHONY : src/app/shortcuts.o

# target to build an object file
src/app/shortcuts.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/shortcuts.cpp.o
.PHONY : src/app/shortcuts.cpp.o

src/app/shortcuts.i: src/app/shortcuts.cpp.i

.PHONY : src/app/shortcuts.i

# target to preprocess a source file
src/app/shortcuts.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/shortcuts.cpp.i
.PHONY : src/app/shortcuts.cpp.i

src/app/shortcuts.s: src/app/shortcuts.cpp.s

.PHONY : src/app/shortcuts.s

# target to generate assembly for a file
src/app/shortcuts.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/shortcuts.cpp.s
.PHONY : src/app/shortcuts.cpp.s

src/app/tabs/camera.o: src/app/tabs/camera.cpp.o

.PHONY : src/app/tabs/camera.o

# target to build an object file
src/app/tabs/camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/tabs/camera.cpp.o
.PHONY : src/app/tabs/camera.cpp.o

src/app/tabs/camera.i: src/app/tabs/camera.cpp.i

.PHONY : src/app/tabs/camera.i

# target to preprocess a source file
src/app/tabs/camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/tabs/camera.cpp.i
.PHONY : src/app/tabs/camera.cpp.i

src/app/tabs/camera.s: src/app/tabs/camera.cpp.s

.PHONY : src/app/tabs/camera.s

# target to generate assembly for a file
src/app/tabs/camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/tabs/camera.cpp.s
.PHONY : src/app/tabs/camera.cpp.s

src/app/tabs/data.o: src/app/tabs/data.cpp.o

.PHONY : src/app/tabs/data.o

# target to build an object file
src/app/tabs/data.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/tabs/data.cpp.o
.PHONY : src/app/tabs/data.cpp.o

src/app/tabs/data.i: src/app/tabs/data.cpp.i

.PHONY : src/app/tabs/data.i

# target to preprocess a source file
src/app/tabs/data.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/tabs/data.cpp.i
.PHONY : src/app/tabs/data.cpp.i

src/app/tabs/data.s: src/app/tabs/data.cpp.s

.PHONY : src/app/tabs/data.s

# target to generate assembly for a file
src/app/tabs/data.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/tabs/data.cpp.s
.PHONY : src/app/tabs/data.cpp.s

src/app/tabs/launcher.o: src/app/tabs/launcher.cpp.o

.PHONY : src/app/tabs/launcher.o

# target to build an object file
src/app/tabs/launcher.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/tabs/launcher.cpp.o
.PHONY : src/app/tabs/launcher.cpp.o

src/app/tabs/launcher.i: src/app/tabs/launcher.cpp.i

.PHONY : src/app/tabs/launcher.i

# target to preprocess a source file
src/app/tabs/launcher.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/tabs/launcher.cpp.i
.PHONY : src/app/tabs/launcher.cpp.i

src/app/tabs/launcher.s: src/app/tabs/launcher.cpp.s

.PHONY : src/app/tabs/launcher.s

# target to generate assembly for a file
src/app/tabs/launcher.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/tabs/launcher.cpp.s
.PHONY : src/app/tabs/launcher.cpp.s

src/app/tabs/media.o: src/app/tabs/media.cpp.o

.PHONY : src/app/tabs/media.o

# target to build an object file
src/app/tabs/media.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/tabs/media.cpp.o
.PHONY : src/app/tabs/media.cpp.o

src/app/tabs/media.i: src/app/tabs/media.cpp.i

.PHONY : src/app/tabs/media.i

# target to preprocess a source file
src/app/tabs/media.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/tabs/media.cpp.i
.PHONY : src/app/tabs/media.cpp.i

src/app/tabs/media.s: src/app/tabs/media.cpp.s

.PHONY : src/app/tabs/media.s

# target to generate assembly for a file
src/app/tabs/media.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/tabs/media.cpp.s
.PHONY : src/app/tabs/media.cpp.s

src/app/tabs/openauto.o: src/app/tabs/openauto.cpp.o

.PHONY : src/app/tabs/openauto.o

# target to build an object file
src/app/tabs/openauto.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/tabs/openauto.cpp.o
.PHONY : src/app/tabs/openauto.cpp.o

src/app/tabs/openauto.i: src/app/tabs/openauto.cpp.i

.PHONY : src/app/tabs/openauto.i

# target to preprocess a source file
src/app/tabs/openauto.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/tabs/openauto.cpp.i
.PHONY : src/app/tabs/openauto.cpp.i

src/app/tabs/openauto.s: src/app/tabs/openauto.cpp.s

.PHONY : src/app/tabs/openauto.s

# target to generate assembly for a file
src/app/tabs/openauto.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/tabs/openauto.cpp.s
.PHONY : src/app/tabs/openauto.cpp.s

src/app/tabs/settings.o: src/app/tabs/settings.cpp.o

.PHONY : src/app/tabs/settings.o

# target to build an object file
src/app/tabs/settings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/tabs/settings.cpp.o
.PHONY : src/app/tabs/settings.cpp.o

src/app/tabs/settings.i: src/app/tabs/settings.cpp.i

.PHONY : src/app/tabs/settings.i

# target to preprocess a source file
src/app/tabs/settings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/tabs/settings.cpp.i
.PHONY : src/app/tabs/settings.cpp.i

src/app/tabs/settings.s: src/app/tabs/settings.cpp.s

.PHONY : src/app/tabs/settings.s

# target to generate assembly for a file
src/app/tabs/settings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/tabs/settings.cpp.s
.PHONY : src/app/tabs/settings.cpp.s

src/app/theme.o: src/app/theme.cpp.o

.PHONY : src/app/theme.o

# target to build an object file
src/app/theme.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/theme.cpp.o
.PHONY : src/app/theme.cpp.o

src/app/theme.i: src/app/theme.cpp.i

.PHONY : src/app/theme.i

# target to preprocess a source file
src/app/theme.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/theme.cpp.i
.PHONY : src/app/theme.cpp.i

src/app/theme.s: src/app/theme.cpp.s

.PHONY : src/app/theme.s

# target to generate assembly for a file
src/app/theme.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/theme.cpp.s
.PHONY : src/app/theme.cpp.s

src/app/widgets/color_label.o: src/app/widgets/color_label.cpp.o

.PHONY : src/app/widgets/color_label.o

# target to build an object file
src/app/widgets/color_label.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/widgets/color_label.cpp.o
.PHONY : src/app/widgets/color_label.cpp.o

src/app/widgets/color_label.i: src/app/widgets/color_label.cpp.i

.PHONY : src/app/widgets/color_label.i

# target to preprocess a source file
src/app/widgets/color_label.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/widgets/color_label.cpp.i
.PHONY : src/app/widgets/color_label.cpp.i

src/app/widgets/color_label.s: src/app/widgets/color_label.cpp.s

.PHONY : src/app/widgets/color_label.s

# target to generate assembly for a file
src/app/widgets/color_label.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/widgets/color_label.cpp.s
.PHONY : src/app/widgets/color_label.cpp.s

src/app/widgets/dialog.o: src/app/widgets/dialog.cpp.o

.PHONY : src/app/widgets/dialog.o

# target to build an object file
src/app/widgets/dialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/widgets/dialog.cpp.o
.PHONY : src/app/widgets/dialog.cpp.o

src/app/widgets/dialog.i: src/app/widgets/dialog.cpp.i

.PHONY : src/app/widgets/dialog.i

# target to preprocess a source file
src/app/widgets/dialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/widgets/dialog.cpp.i
.PHONY : src/app/widgets/dialog.cpp.i

src/app/widgets/dialog.s: src/app/widgets/dialog.cpp.s

.PHONY : src/app/widgets/dialog.s

# target to generate assembly for a file
src/app/widgets/dialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/widgets/dialog.cpp.s
.PHONY : src/app/widgets/dialog.cpp.s

src/app/widgets/ip_input.o: src/app/widgets/ip_input.cpp.o

.PHONY : src/app/widgets/ip_input.o

# target to build an object file
src/app/widgets/ip_input.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/widgets/ip_input.cpp.o
.PHONY : src/app/widgets/ip_input.cpp.o

src/app/widgets/ip_input.i: src/app/widgets/ip_input.cpp.i

.PHONY : src/app/widgets/ip_input.i

# target to preprocess a source file
src/app/widgets/ip_input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/widgets/ip_input.cpp.i
.PHONY : src/app/widgets/ip_input.cpp.i

src/app/widgets/ip_input.s: src/app/widgets/ip_input.cpp.s

.PHONY : src/app/widgets/ip_input.s

# target to generate assembly for a file
src/app/widgets/ip_input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/widgets/ip_input.cpp.s
.PHONY : src/app/widgets/ip_input.cpp.s

src/app/widgets/progress.o: src/app/widgets/progress.cpp.o

.PHONY : src/app/widgets/progress.o

# target to build an object file
src/app/widgets/progress.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/widgets/progress.cpp.o
.PHONY : src/app/widgets/progress.cpp.o

src/app/widgets/progress.i: src/app/widgets/progress.cpp.i

.PHONY : src/app/widgets/progress.i

# target to preprocess a source file
src/app/widgets/progress.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/widgets/progress.cpp.i
.PHONY : src/app/widgets/progress.cpp.i

src/app/widgets/progress.s: src/app/widgets/progress.cpp.s

.PHONY : src/app/widgets/progress.s

# target to generate assembly for a file
src/app/widgets/progress.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/widgets/progress.cpp.s
.PHONY : src/app/widgets/progress.cpp.s

src/app/widgets/switch.o: src/app/widgets/switch.cpp.o

.PHONY : src/app/widgets/switch.o

# target to build an object file
src/app/widgets/switch.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/widgets/switch.cpp.o
.PHONY : src/app/widgets/switch.cpp.o

src/app/widgets/switch.i: src/app/widgets/switch.cpp.i

.PHONY : src/app/widgets/switch.i

# target to preprocess a source file
src/app/widgets/switch.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/widgets/switch.cpp.i
.PHONY : src/app/widgets/switch.cpp.i

src/app/widgets/switch.s: src/app/widgets/switch.cpp.s

.PHONY : src/app/widgets/switch.s

# target to generate assembly for a file
src/app/widgets/switch.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/widgets/switch.cpp.s
.PHONY : src/app/widgets/switch.cpp.s

src/app/widgets/tuner.o: src/app/widgets/tuner.cpp.o

.PHONY : src/app/widgets/tuner.o

# target to build an object file
src/app/widgets/tuner.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/widgets/tuner.cpp.o
.PHONY : src/app/widgets/tuner.cpp.o

src/app/widgets/tuner.i: src/app/widgets/tuner.cpp.i

.PHONY : src/app/widgets/tuner.i

# target to preprocess a source file
src/app/widgets/tuner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/widgets/tuner.cpp.i
.PHONY : src/app/widgets/tuner.cpp.i

src/app/widgets/tuner.s: src/app/widgets/tuner.cpp.s

.PHONY : src/app/widgets/tuner.s

# target to generate assembly for a file
src/app/widgets/tuner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/widgets/tuner.cpp.s
.PHONY : src/app/widgets/tuner.cpp.s

src/app/window.o: src/app/window.cpp.o

.PHONY : src/app/window.o

# target to build an object file
src/app/window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/window.cpp.o
.PHONY : src/app/window.cpp.o

src/app/window.i: src/app/window.cpp.i

.PHONY : src/app/window.i

# target to preprocess a source file
src/app/window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/window.cpp.i
.PHONY : src/app/window.cpp.i

src/app/window.s: src/app/window.cpp.s

.PHONY : src/app/window.s

# target to generate assembly for a file
src/app/window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/window.cpp.s
.PHONY : src/app/window.cpp.s

src/canbus/socketcanbus.o: src/canbus/socketcanbus.cpp.o

.PHONY : src/canbus/socketcanbus.o

# target to build an object file
src/canbus/socketcanbus.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/canbus/socketcanbus.cpp.o
.PHONY : src/canbus/socketcanbus.cpp.o

src/canbus/socketcanbus.i: src/canbus/socketcanbus.cpp.i

.PHONY : src/canbus/socketcanbus.i

# target to preprocess a source file
src/canbus/socketcanbus.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/canbus/socketcanbus.cpp.i
.PHONY : src/canbus/socketcanbus.cpp.i

src/canbus/socketcanbus.s: src/canbus/socketcanbus.cpp.s

.PHONY : src/canbus/socketcanbus.s

# target to generate assembly for a file
src/canbus/socketcanbus.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/canbus/socketcanbus.cpp.s
.PHONY : src/canbus/socketcanbus.cpp.s

src/ia.o: src/ia.cpp.o

.PHONY : src/ia.o

# target to build an object file
src/ia.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/ia.cpp.o
.PHONY : src/ia.cpp.o

src/ia.i: src/ia.cpp.i

.PHONY : src/ia.i

# target to preprocess a source file
src/ia.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/ia.cpp.i
.PHONY : src/ia.cpp.i

src/ia.s: src/ia.cpp.s

.PHONY : src/ia.s

# target to generate assembly for a file
src/ia.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/ia.cpp.s
.PHONY : src/ia.cpp.s

src/obd/command.o: src/obd/command.cpp.o

.PHONY : src/obd/command.o

# target to build an object file
src/obd/command.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/obd/command.cpp.o
.PHONY : src/obd/command.cpp.o

src/obd/command.i: src/obd/command.cpp.i

.PHONY : src/obd/command.i

# target to preprocess a source file
src/obd/command.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/obd/command.cpp.i
.PHONY : src/obd/command.cpp.i

src/obd/command.s: src/obd/command.cpp.s

.PHONY : src/obd/command.s

# target to generate assembly for a file
src/obd/command.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/obd/command.cpp.s
.PHONY : src/obd/command.cpp.s

src/obd/obd.o: src/obd/obd.cpp.o

.PHONY : src/obd/obd.o

# target to build an object file
src/obd/obd.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/obd/obd.cpp.o
.PHONY : src/obd/obd.cpp.o

src/obd/obd.i: src/obd/obd.cpp.i

.PHONY : src/obd/obd.i

# target to preprocess a source file
src/obd/obd.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/obd/obd.cpp.i
.PHONY : src/obd/obd.cpp.i

src/obd/obd.s: src/obd/obd.cpp.s

.PHONY : src/obd/obd.s

# target to generate assembly for a file
src/obd/obd.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/obd/obd.cpp.s
.PHONY : src/obd/obd.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... InfinitiG37_autogen"
	@echo "... KF5BluezQt_QCH"
	@echo "... ia_autogen"
	@echo "... InfinitiG37"
	@echo "... ia"
	@echo "... InfinitiG37_autogen/mocs_compilation.o"
	@echo "... InfinitiG37_autogen/mocs_compilation.i"
	@echo "... InfinitiG37_autogen/mocs_compilation.s"
	@echo "... ia_autogen/GBFAFXFCVO/qrc_resources.o"
	@echo "... ia_autogen/GBFAFXFCVO/qrc_resources.i"
	@echo "... ia_autogen/GBFAFXFCVO/qrc_resources.s"
	@echo "... ia_autogen/mocs_compilation.o"
	@echo "... ia_autogen/mocs_compilation.i"
	@echo "... ia_autogen/mocs_compilation.s"
	@echo "... plugins/infiniti_g37.o"
	@echo "... plugins/infiniti_g37.i"
	@echo "... plugins/infiniti_g37.s"
	@echo "... src/app/bluetooth.o"
	@echo "... src/app/bluetooth.i"
	@echo "... src/app/bluetooth.s"
	@echo "... src/app/config.o"
	@echo "... src/app/config.i"
	@echo "... src/app/config.s"
	@echo "... src/app/modules/brightness.o"
	@echo "... src/app/modules/brightness.i"
	@echo "... src/app/modules/brightness.s"
	@echo "... src/app/shortcuts.o"
	@echo "... src/app/shortcuts.i"
	@echo "... src/app/shortcuts.s"
	@echo "... src/app/tabs/camera.o"
	@echo "... src/app/tabs/camera.i"
	@echo "... src/app/tabs/camera.s"
	@echo "... src/app/tabs/data.o"
	@echo "... src/app/tabs/data.i"
	@echo "... src/app/tabs/data.s"
	@echo "... src/app/tabs/launcher.o"
	@echo "... src/app/tabs/launcher.i"
	@echo "... src/app/tabs/launcher.s"
	@echo "... src/app/tabs/media.o"
	@echo "... src/app/tabs/media.i"
	@echo "... src/app/tabs/media.s"
	@echo "... src/app/tabs/openauto.o"
	@echo "... src/app/tabs/openauto.i"
	@echo "... src/app/tabs/openauto.s"
	@echo "... src/app/tabs/settings.o"
	@echo "... src/app/tabs/settings.i"
	@echo "... src/app/tabs/settings.s"
	@echo "... src/app/theme.o"
	@echo "... src/app/theme.i"
	@echo "... src/app/theme.s"
	@echo "... src/app/widgets/color_label.o"
	@echo "... src/app/widgets/color_label.i"
	@echo "... src/app/widgets/color_label.s"
	@echo "... src/app/widgets/dialog.o"
	@echo "... src/app/widgets/dialog.i"
	@echo "... src/app/widgets/dialog.s"
	@echo "... src/app/widgets/ip_input.o"
	@echo "... src/app/widgets/ip_input.i"
	@echo "... src/app/widgets/ip_input.s"
	@echo "... src/app/widgets/progress.o"
	@echo "... src/app/widgets/progress.i"
	@echo "... src/app/widgets/progress.s"
	@echo "... src/app/widgets/switch.o"
	@echo "... src/app/widgets/switch.i"
	@echo "... src/app/widgets/switch.s"
	@echo "... src/app/widgets/tuner.o"
	@echo "... src/app/widgets/tuner.i"
	@echo "... src/app/widgets/tuner.s"
	@echo "... src/app/window.o"
	@echo "... src/app/window.i"
	@echo "... src/app/window.s"
	@echo "... src/canbus/socketcanbus.o"
	@echo "... src/canbus/socketcanbus.i"
	@echo "... src/canbus/socketcanbus.s"
	@echo "... src/ia.o"
	@echo "... src/ia.i"
	@echo "... src/ia.s"
	@echo "... src/obd/command.o"
	@echo "... src/obd/command.i"
	@echo "... src/obd/command.s"
	@echo "... src/obd/obd.o"
	@echo "... src/obd/obd.i"
	@echo "... src/obd/obd.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

