name: Nix Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Install Nix
        uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Check flake
        run: nix flake check --print-build-logs

      - name: Build Dash
        run: nix build .#dash --print-build-logs
