name: NixOS Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    paths:
      - ".github/workflows/build.yml"
      - ".github/workflows/images.yml"
      - "CMakeLists.txt"
      - "cmake_modules/**"
      - "flake.lock"
      - "flake.nix"
      - "nix/**"
      - "patches/**"
      - "plugins/CMakeLists.txt"

jobs:
  pi4-headunit:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130
        with:
          platforms: arm64

      - name: Install Nix
        uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            extra-platforms = aarch64-linux

      - name: Build image
        run: nix run .#make-images

      - name: Upload image
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: dash-pi4-headunit-image
          path: dist/images/*.img.zst
          if-no-files-found: error
